CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_SENSOR_LOG_LEVEL_DBG=y
CONFIG_MAX30101=y

CONFIG_SHELL=y
CONFIG_LED_SHELL=y
CONFIG_I2C_SHELL=y
CONFIG_GPIO_SHELL=y
CONFIG_PM_DEVICE_RUNTIME=n
