# For Wi-Fi STA mode
CONFIG_WIFI=y
CONFIG_WIFI_LOG_LEVEL_ERR=y
CONFIG_NET_L2_WIFI_SHELL=y
CONFIG_WIFI_NM_WPA_SUPPLICANT=y
CONFIG_NET_DHCPV4=y

# Wi-Fi STA interface will not be operationally UP till the user connects to an AP
CONFIG_NET_CONFIG_INIT_TIMEOUT=0

# Zperf TCP=6, UDP=2, Others=1
# WPA supplicant: Global ctrl_iface: 2, per interface: 2
CONFIG_ZVFS_OPEN_MAX=20
CONFIG_NET_SOCKETS_POLL_MAX=20
CONFIG_ZVFS_POLL_MAX=20

# Sockets: hostap select + poll take up more stack
CONFIG_MAIN_STACK_SIZE=5200
CONFIG_SHELL_STACK_SIZE=5200
